version: '3.8'
services:
  blog-server:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - ./:project
    command: npm run start
  db:
    image: mysql
    restart: always
    ports:
      - '3306:3306'
    environment:
      - DATABASE_USER:root
      - DATABASE_PASSWORD:123456
      - DATABASE_NAME=test
