version: '3.8'
services:
  db:
    image: mysql
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      - DATABASE_USER=root
      - DATABASE_PASSWORD=123456
      - DATABASE_NAME=test
  blog-server:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - /.:/project:ro
    command: npm run start
