version: '3.8'
services:
  db:
    networks:
      - mysql
    image: mysql
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - $DATABASE_PORT:$DATABASE_PORT
    environment:
      - MYSQL_ROOT_PASSWORD=$DATABASE_PASSWORD
      - MYSQL_DATABASE=$DATABASE_NAME
  server:
    networks:
      - mysql
      - backend
    depends_on:
      - db
    build: .
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - $SERVER_PORT:$SERVER_PORT
networks:
  mysql:
    driver: custom-driver-1
  backend:
    driver: custom-driver-2
