version: '3.8'
services:
  db:
    image: mysql
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123456
      - MYSQL_DATABASE=test
  blog-server:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - /.:/project:ro
